name: QML Format Check

on:
  push:
    branches: [ master ]

jobs:
  qml-format-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        modules: 'qtdeclarative'
    
    - name: Find QML files
      id: find-qml
      run: |
        echo "Found QML files:"
        find . -name "*.qml" -type f
    
    - name: Check QML formatting
      run: |
        EXIT_CODE=0
        FILES=$(find . -name "*.qml" -type f)
        
        if [ -z "$FILES" ]; then
          echo "No QML files found"
          exit 0
        fi
        
        for file in $FILES; do
          echo "Checking $file..."
          
          qmlformat "$file" > /tmp/formatted.qml
          
          if ! diff -u "$file" /tmp/formatted.qml; then
            echo "$file is not properly formatted"
            EXIT_CODE=1
          else
            echo "$file is properly formatted"
          fi
        done
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo ""
          echo "==================================="
          echo "Some QML files are not formatted correctly."
          echo "Run 'qmlformat -i <file>' to fix formatting."
          echo "==================================="
        fi
        
        exit $EXIT_CODE
